### ISSUE TITLE
[1.15.2]party exp

### ISSUE THREAD

**Issue by mcfensi** [RobertSkalko/Mine-and-Slash#155]
3.1.8
* added party exp sharing if nearby.

I used 3.1.10 to test in LAN, This update did not take effect.

**Comment by mcfensi** [comment]
I tested in 3.1.11 and still no exp sharing

**Comment by mcfensi** [comment]
I tested in 3.1.12 and still no exp sharing

**Comment by mcfensi** [comment]
It seems that my experience has decreased, but other party players have not increased.

**Comment by RobertSkalko** [comment]
I see the problem now, should be fixed in next update

**Comment by mcfensi** [comment]
I tested in 3.1.13 and still no exp sharing

**Comment by RobertSkalko** [comment]
Are you sure? I only show the floating numbers for the one that kills the mob but xp should still go to others in party

**Comment by mcfensi** [comment]
yes, I'm sure. I tested it again just now, but still not. I'm sure it's in a party and another player is right next to it.

**Comment by mcfensi** [comment]
3.1.14 After testing, it can be normal exp sharing. But it seems a little too far away, I have exp sharing from x: -8 y: 241 to x: -256 y: 2203

**Comment by RobertSkalko** [comment]
Ok but it works, so i'm closing the issue.
